### ISSUE TITLE
Undefined instruction when using UPX with aarch64

### ISSUE THREAD

**Issue by agherzan** [upx/upx#130]
## What's the problem (or question)?

We compress with upx (3.94) some go binaries. One of them is an init binary which managed root filesystems as docker images (https://github.com/resin-os/balaena/blob/17.06-resin/cmd/mobynit/main.go). When running the binary without compressing it with UPX everything works fine. If we compress it using `--best -q` as arguments, we end up in the following error:

```
root@resin:/tmp/bin# ./init
[ 1325.613969] init_stripped[1142]: undefined instruction: pc=0000000000b42000
[ 1325.621351] Code: 54ffff43 71000c23 52800001 54000123 (38401405)
Illegal instruction (core dumped)
```

## What should have happened?

UPXed binaries should work for aarch64.

## How can we reproduce the issue?

1. 
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: ArchLinux
* Host CPU architecture: amd64
* Target Operating System and version: resinOS
* Target CPU architecture: aarch64

**Comment by jreiser** [comment]
@agherzan Please build (compile+link), gzip, and upload ("Attach files ...") that program here.  Having the exact input to upx will make it much easier to diagnose the problem.  Thank you.

**Comment by jreiser** [comment]
When assembled and disasembled, the instructions in the original posting are:
```
	.word 0x54ffff43,0x71000c23,0x52800001,0x54000123,0x38401405

(gdb) x/5i 0
   0x0:	b.cc	0xffffffffffffffe8  // b.lo, b.ul, b.last
   0x4:	subs	w3, w1, #0x3
   0x8:	mov	w1, #0x0                   	// #0
   0xc:	b.cc	0x30  // b.lo, b.ul, b.last
   0x10:	ldrb	w5, [x0], #1
```
which all look OK.

**Comment by jreiser** [comment]
@agherzan  When I use golang-bin-1.9.1-1.fc27.aarch64 to "go run src/main.go" with the mobynit/main.go of the original posting, and having gotten the packages, then I see:
```
$ go get github.com/docker/docker/daemon/graphdriver/aufs
$ go get github.com/docker/docker/daemon/graphdriver/overlay2
$ go get github.com/docker/docker/layer
$ go get github.com/docker/docker/pkg/idtools
$ go get github.com/docker/docker/pkg/mount
$ go get golang.org/x/sys/unix

$ go run src/main.go
# command-line-arguments
src/main.go:39:11: unknown field 'Platform' in struct literal of type layer.StoreOptions
src/main.go:55:23: cannot use newRoot (type containerfs.ContainerFS) as type string in argument to unix.Mount
src/main.go:58:19: cannot use newRoot (type containerfs.ContainerFS) as type string in argument to unix.Mount
src/main.go:60:37: cannot use newRoot (type containerfs.ContainerFS) as type string in argument to filepath.Join
src/main.go:64:2: cannot use newRoot (type containerfs.ContainerFS) as type string in return argument
```
What am I missing?

**Comment by agherzan** [comment]
I'll come back with a minimum taste case soon. A flu struck in the meanwhile. Forgive my initial laziness.

**Comment by jreiser** [comment]
@agherzan Ping? Have you been able to make a test case?  "Minimal" is nice, but anything small-ish (compress using gzip or zip before Attach-ing the file here) will serve, too.

**Comment by jreiser** [comment]
@agherzan Another ping?  If you cannot Attach a test case then please run under a debugger such as gdb or lldb, and show the state at the time of the crash.  In gdb this would be
```
(gdb) x/5i $pc  # current and next instructions
(gdb) x/12i $pc-12*4  # likely previous instructions
(gdb) info reg  # all registers
(gdb) x/16xw $sp  # top of stack
(gdb) bt  # backtrace of subroutine calls
(gdb) info proc  # process ID and other info
(gdb) shell cat /proc/PID/maps  # PID is process ID from "info proc"
```

**Comment by agherzan** [comment]
I finally have a minimum usecase and results with gdb. The minimum source code is:
```
package main

import (
        "github.com/docker/docker/pkg/mount"
        "fmt"
)

func main() {
        mounts, _ := mount.GetMounts()
        fmt.Println(mounts[0].Root)
}
```

This tiny program runs fine before getting upx'ed. I use `--best` when compressing it and as soon as I try to run it it fails with SIGILL. Here are the results from gdb:

```
(gdb) x/5i $pc
=> 0x1d71bc:    str     x30, [sp,#-16]!
   0x1d71c0:    stp     x2, x3, [sp,#-16]!
   0x1d71c4:    add     x7, x0, w1, uxtw
   0x1d71c8:    mov     w5, #0xffffffff                 // #-1
   0x1d71cc:    mov     w4, #0x80000000                 // #-2147483648
(gdb) x/12i $pc-12*4
   0x1d718c:    add     w10, w10, #0x58
   0x1d7190:    sub     w9, w29, w10
   0x1d7194:    add     x10, x12, w10, uxtw
   0x1d7198:    add     x10, x10, x4
   0x1d719c:    ldr     w4, [x11,#8]
   0x1d71a0:    ldr     w3, [x11]
   0x1d71a4:    add     x0, x11, #0xc
   0x1d71a8:    ldr     w1, [x11,#4]
   0x1d71ac:    mov     x2, x30
   0x1d71b0:    str     w3, [sp,#16]
   0x1d71b4:    add     x3, sp, #0x10
   0x1d71b8:    br      x15
(gdb) info reg
x0             0x773cc  488396
x1             0x6a3    1699
x2             0x1d7304 1929988
x3             0x7ffffffca0     549755813024
x4             0x5208   21000
x5             0x772c0  488128
x6             0x0      0
x7             0x0      0
x8             0xde     222
x9             0x66fcc  421836
x10            0x170100 1507584
x11            0x773c0  488384
x12            0x10000  65536
x13            0x22     34
x14            0x0      0
x15            0x1d71bc 1929660
x16            0x0      0
x17            0x0      0
x18            0x0      0
x19            0x0      0
x20            0x0      0
x21            0x0      0
x22            0x0      0
x23            0x0      0
x24            0x0      0
x25            0x0      0
x26            0x0      0
x27            0x0      0
x28            0x0      0
x29            0x670cc  422092
x30            0x1d7304 1929988
sp             0x7ffffffc90     0x7ffffffc90
pc             0x1d71bc 0x1d71bc
cpsr           0x20000000       [ EL=0 C ]
fpsr           0x0      0
fpcr           0x0      0
(gdb) x/16xw $sp
0x7ffffffc90:   0x00170000      0x00000000      0x0006894c      0x00000000
0x7ffffffca0:   0x00000880      0x00000000      0x00000022      0x00000000
0x7ffffffcb0:   0x00000001      0x00000000      0xfffffe99      0x0000007f
0x7ffffffcc0:   0x00000000      0x00000000      0xfffffea6      0x0000007f
(gdb) bt
#0  0x00000000001d71bc in ?? ()
#1  0x0980411e3b1a4353 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info proc
process 1861
cmdline = '/tmp/mobynit'
cwd = '/home/root'
exe = '/tmp/mobynit'
(gdb) shell cat /proc/1861/maps
00010000-00078000 r-xp 00000000 00:1d 34667                              /tmp/mobynit
0015f000-00160000 rw-p 0000f000 00:1d 34667                              /tmp/mobynit
00170000-001d9000 rwxp 00000000 00:00 0 
7fb7fff000-7fb8000000 r--p 00000000 00:00 0                              [vvar]
7fb8000000-7fb8001000 r-xp 00000000 00:00 0                              [vdso]
7ffffdf000-8000000000 rw-p 00000000 00:00 0                              [stack]
```

**Comment by jreiser** [comment]
@agherzan The tip of branch <tt>devel</tt> works for me; please try that.  There was a major strategy change for runtime decompression in 402c88598754efa41828734f149600ef5bf34d72 on Oct.14 which could easily account for the success (although I did not run a <tt>git bisect</tt> to find exactly where.)
```
(gdb) run
Starting program: /path/to/github-issue130/main
[New LWP 1552]
[New LWP 1553]
[New LWP 1554]
[New LWP 1555]
[New LWP 1556]
/
[LWP 1556 exited]
[LWP 1555 exited]
[LWP 1553 exited]
[LWP 1552 exited]
[LWP 1549 exited]
[Inferior 1 (process 1549) exited normally]
(gdb)
```

**Comment by agherzan** [comment]
I confirm it works with the devel branch.

**Comment by agherzan** [comment]
I investigated a little the issue and with bisect I found that the fixing commit is:
```
Author:     John Reiser <jreiser@BitWagon.com>                                                                                                        
AuthorDate: Tue Oct 10 14:51:03 2017 -0700                                                                                                            
Commit:     John Reiser <jreiser@BitWagon.com>                                                                                                        
CommitDate: Tue Oct 10 14:51:03 2017 -0700                                                                                                            
                                                                    
    arm64: stub uses new strategy                                                                                 
                                                                                       
        modified:   p_lx_elf.cpp                                                                                  
        modified:   stub/src/powerpc64le-linux.elf-entry.S                                                  
        modified:   stub/src/amd64-linux.elf-main.c                                            
        modified:   stub/src/arm64-linux.elf-entry.S                                                    
        modified:   stub/src/arm64-linux.elf-fold.S                               
        modified:   stub/src/arm64-linux.elf-main.c                              
        also .h, .map, .bin.dump
```

What are the plans of including this fix in a release?

**Comment by jreiser** [comment]
As long as experience continues to be good, then the devel branch will become the next release, which might happen in a small number of months.  Compression for ELF format has been improving and expanding (see the Fixed issues versus the Open issues) and this is a good sign.  Compression for PE format (Windows) is stalled with a number of issues, so some management decision may be necessary.

**Comment by agherzan** [comment]
"small number of months" - that sounds like a long time. Thanks anyway for the feedback and support.
