### ISSUE TITLE
Heap out of bounds read in function get_le16()

### ISSUE THREAD

**Issue by fumfel** [upx/upx#151]
## What's the problem (or question)?

Heap out of bounds read in function get_le16()

## What should have happened?

```
==7962==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x632000016aec at pc 0x0000006f93b5 bp 0x7fffd355caa0 sp 0x7fffd355ca90
READ of size 2 at 0x632000016aec thread T0
    #0 0x6f93b4 in get_le16(void const*) XYZ/upx/src/bele.h:112
    #1 0x6f93b4 in LE16::operator unsigned int() const XYZ/upx/src/bele.h:398
    #2 0x6f93b4 in PeFile::Reloc::next(unsigned int&, unsigned int&) XYZ/upx/src/pefile.cpp:305
    #3 0x6f97bd in PeFile::Reloc::Reloc(unsigned char*, unsigned int) XYZ/upx/src/pefile.cpp:287
    #4 0x70587b in PeFile::processLoadConf(PeFile::Interval*) XYZ/upx/src/pefile.cpp:1436
    #5 0x732fb9 in void PeFile::pack0<LE32, PeFile32::pe_header_t>(OutputFile*, PeFile32::pe_header_t&, PeFile32::pe_header_t&, unsigned int, unsigned long long, bool) XYZ/upx/src/pefile.cpp:2258
    #6 0x72e90d in PeFile32::pack0(OutputFile*, unsigned int, unsigned long long, bool) XYZ/upx/src/pefile.cpp:3103
    #7 0x6cdf69 in Packer::doPack(OutputFile*) XYZ/upx/src/packer.cpp:100
    #8 0x78a03e in do_one_file(char const*, char*) XYZ/upx/src/work.cpp:158
    #9 0x78a9e2 in do_files(int, int, char**) XYZ/upx/src/work.cpp:271
    #10 0x407154 in main XYZ/upx/src/main.cpp:1535
    #11 0x7fbf5eec982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x409618 in _start (/root/upx/src/upx.out+0x409618)

0x632000016aec is located 0 bytes to the right of 90860-byte region [0x632000000800,0x632000016aec)
allocated by thread T0 here:
    #0 0x7fbf5fabd602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x5106a5 in MemBuffer::alloc(unsigned long long) XYZ/upx/src/mem.cpp:194

SUMMARY: AddressSanitizer: heap-buffer-overflow XYZ/upx/src/bele.h:112 get_le16(void const*)
Shadow bytes around the buggy address:
  0x0c647fffad00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c647fffad10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c647fffad20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c647fffad30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c647fffad40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c647fffad50: 00 00 00 00 00 00 00 00 00 00 00 00 00[04]fa fa
  0x0c647fffad60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c647fffad70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c647fffad80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c647fffad90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c647fffada0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==7962==ABORTING
```

## How can we reproduce the issue?

1. Download file: https://frankowicz.me/storage/crashes/upx_hoobr_get_le16
2. Run it with upx: `upx upx_hoobr_get_le16`
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.95-git-6eafa552bb4b
* Host Operating System and version: Ubuntu 16.04
* Host CPU architecture: x64 / Compiled with Clang 5.0 + ASAN
* Target Operating System and version: Ubuntu 16.04
* Target CPU architecture: x64 / Compiled with Clang 5.0 + ASAN

**Comment by jreiser** [comment]
@fumfel What is the file type of upx_hoobr_get_le16 ?  It does have "PE\0\0" at offset 0x36e, but isn't recognized as a PE file.
```
$ upx -D upx_hoobr_get_le16  # -D: diagnose file types for packing
UPX git-6eafa5+ Markus Oberhumer, Laszlo Molnar & John Reiser   May 13th 2017

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64Pep
visitAllPackers: (ver=13, fmt=  9) PackW32Pe
visitAllPackers: (ver=13, fmt= 21) PackArmPe
visitAllPackers: (ver=13, fmt=  3) PackExe
upx.out: upx_hoobr_get_le16: CantPackException: can't pack new-exe
```

**Comment by jreiser** [comment]
Not enough information.
