### ISSUE TITLE
nexe

### ISSUE THREAD

**Issue by cris691** [upx/upx#386]
## What's the problem (or question)?

I use nexe to build JS into executables. Then use upx to make these smaller.
UPX made a Windows executable smaller and work fine.
UPX made a Linux executable much smaller and it did not work. 

## What should have happened?

The executable should have worked.

## Do you have an idea for a solution?

No idea. 

## How can we reproduce the issue?

Using Debian linux x64 box (with nodejs, and nvm installed)

1. git clone https://github.com/dosyago/BrowserGap && cd BrowserGap
2. git fetch --all && git checkout nexe-build
3. npm i *say yes to setup_machine*
4. nvm install v12.10.0 && nvm use v12.10.0
5. npm run build *builds the executables with nexe*
6. ./BrowserGap.nix *it works (go to localhost:8002)*
6. npm run pack *uses upx to make them better*
7. ./BrowserGap.nix *run the linux-x64 exe again, it does not work*
 
*notice the error*

## Please tell us details about your environment.

UPX 
```text
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
```

`npx envinfo --binaries --languages --system --utilities`:
```text
npx: installed 1 in 1.101s

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Xeon(R) CPU @ 2.00GHz
    Memory: 27.38 GB / 29.45 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Utilities:
    CMake: 3.13.4 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 5.0.3 - /bin/bash
    Perl: 5.28.1 - /usr/bin/perl
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
```

**Comment by cris691** [comment]
BTW, upx is just the best. I'm so grateful you guys created it. I've been using it to make binaries for other projects that work totally fine! Love upx. 👍

**Comment by cris691** [comment]
**Additional instructions:**

You also need to have npx installed

`npm i -g npx`

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or provide a URL for an actual file which triggers your complaint about UPX.  Compress the upload with gzip, zip, or .tgz to save space.
Your reply to "How can we reproduce the issue?" does not work:
```
user@host.domain:/bigdata/BrowserGap
$ git branch
  master
* nexe-build
user@host.domain:/bigdata/BrowserGap
$ git log
commit 6fbe82194e6e718245f2a4ba4e300c19b371f0d5 (HEAD -> nexe-build, origin/nexe-build)
Author: Cris Stringfellow <22254235+crislin2046@users.noreply.github.com>
Date:   Sat Jul 18 11:00:59 2020 +0000
   [[snip]]
user@host.domain:/bigdata/BrowserGap
$ rpm -qf /usr/bin/npm
npm-6.13.4-1.10.19.0.1.fc30.x86_64
user@host.domain:/bigdata/BrowserGap
$ nvm install v12.10.0
Downloading and installing node v12.10.0...
Downloading https://nodejs.org/dist/v12.10.0/node-v12.10.0-linux-x64.tar.xz...
########################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
nvm is not compatible with the npm config "prefix" option: currently set to "/bigdata/home/jreiser/.nvm/versions/node/v12.10.0"
Run `npm config delete prefix` or `nvm use --delete-prefix v12.10.0` to unset it.
user@host.domain:/bigdata/BrowserGap
$ npm config delete prefix
user@host.domain:/bigdata/BrowserGap
$ nvm use v12.10.0
nvm is not compatible with the npm config "prefix" option: currently set to "/bigdata/home/jreiser/.nvm/versions/node/v12.10.0"
Run `npm config delete prefix` or `nvm use --delete-prefix v12.10.0` to unset it.
user@host.domain:/bigdata/BrowserGap
$ npm run build

> remoteview@2.14.0 build /bigdata/BrowserGap
> npx webpack server.js && nexe -t linux-x64 -o BrowserGap.nix -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t windows -o BrowserGap.exe -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t macos-x64 -o BrowserGap.macos -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t windows-x32 -o BrowserGap.win32.exe -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t linux-x32 -o BrowserGap.nix32 -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*"

npx: installed 343 in 12.746s
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack-cli@3.3.12
added 789 packages from 479 contributors and audited 792 packages in 14.606s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at runCommand.then (/bigdata/home/jreiser/.npm/_npx/18519/lib/node_modules/webpack/bin/webpack.js:143:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remoteview@2.14.0 build: `npx webpack server.js && nexe -t linux-x64 -o BrowserGap.nix -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t windows -o BrowserGap.exe -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t macos-x64 -o BrowserGap.macos -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t windows-x32 -o BrowserGap.win32.exe -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*" && nexe -t linux-x32 -o BrowserGap.nix32 -i BrowserGap.js -r "./zombie-lord/injections/**/*" -r "./plugins/**/*.js" -r "./public/**/*"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remoteview@2.14.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jreiser/.npm/_logs/2020-07-18T15_11_49_592Z-debug.log
user@host.domain:/bigdata/BrowserGap
$ 
```

**Comment by cris691** [comment]
Sorry about that. I'll update.

**Comment by cris691** [comment]
I think you need to run `npm i` before `npm run build`

Here's a zip of the Linux-x64 binary built with nexe that (if you then pack it with upx) will say "Invalid binary"

[BrowserGap.zip](https://github.com/upx/upx/files/4943497/BrowserGap.zip)

**Comment by jreiser** [comment]
The tip of `devel` branch works for me:
```
$ ../upx.out -f -o foo BrowserGap.nix
UPX git-4e1ae2+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  51043272 ->  18044432   35.35%   linux/amd64   foo
```

**Comment by cris691** [comment]
Thank you. 

I can add that a workaround I used was: first compress the Node binaries used by nexe, before they are combined with my NodeJS source code. And don't pack after. Doing it this also made it quite small. Good to know upx is working upstream. 

Um, btw, I'm curious how UPX works, is there a good place to go for info on that?

**Comment by jreiser** [comment]
<i>I'm curious how UPX works ...</i> UPX chooses among several compression algorithms; most are based on`deflate`, with different algorithms for encoding the result.  The real fun begins when a compressed program is executed.  A small run-time supervisor de-compresses and arranges the memory image so that it is identical to the non-compressed version, then unmaps itself just before transferring control to the beginning of the program.  The mechanics of doing this are in the src/stub/src directory; for ELF programs see *-entry.S, *-fold.S, and *-main.c.
