### ISSUE TITLE
rebuild stub  failed at xstrip.py

### ISSUE THREAD

**Issue by heysion** [upx/upx#488]
## What's the problem (or question)?

on rebuild stub found this error.
```code
python ./../../src/stub/scripts/xstrip.py --with-dump=tmp/arm64-linux.elf-entry.bin.dump tmp/arm64-linux.elf-entry.bin
e_shnum:22,e_shstrndx:21
Traceback (most recent call last):
  File "./../../src/stub/scripts/xstrip.py", line 222, in <module>
    sys.exit(main(sys.argv))
  File "./../../src/stub/scripts/xstrip.py", line 216, in main
    do_file(arg)
  File "./../../src/stub/scripts/xstrip.py", line 159, in do_file
    assert e_shstrndx + 3 == e_shnum
AssertionError
make: *** [Makefile:562: arm64-linux.elf-entry.h] Error 1
```

## What should have happened?

The e_shnum  has e_shstrndx - 1  ==  e_shnum  .
but the code written like this.
assert e_shstrndx + 3 == e_shnum  

```code
readelf  -h tmp/arm64-linux.elf-entry.bin
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          6392 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         22
  Section header string table index: 21
```

## Do you have an idea for a solution?

modify src/stub/scripts/xstrip.py do_file method.
but not sure this modify has correct .

## How can we reproduce the issue?

1. cd src/stub
2.  rm  arm64-linux.elf-entry.h -v
3.  make arm64-linux.elf-entry.h
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94  tools : upx-20210104
* Host Operating System and version: debian 10
* Host CPU architecture: arm64
* Target Operating System and version: arm64
* Target CPU architecture: arm64

**Comment by jreiser** [comment]
It works for me using upx-stubtools-20210104.
```
$ strace -f -o strace.out make arm64-linux.elf-entry.h   # remade with same contents and no complaints
$ grep execve strace.out  |  sed s/<my-$HOME>/\$HOME/g
16344 execve("$HOME/local/bin/bin-upx/arm64-linux-gcc-4.9.2", ["arm64-linux-gcc-4.9.2", "-nostdinc", "-MMD", "-MT", "arm64-linux.elf-entry.h", "-fno-exceptions", "-fno-asynchronous-unwind-tables", "-Wall", "-W", "-Wcast-align", "-Wcast-qual", "-Wstrict-prototypes", "-Wwrite-strings", "-Werror", "-c", "src/arm64-linux.elf-entry.S", "-o", "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16344 <... execve resumed>)             = 0
16345 execve("$HOME/local/bin/bin-upx-20210104/packages/gcc-aarch64-linux-gnu-4.9.2-3.fc22.x86_64/bin/../libexec/gcc/aarch64-linux-gnu/4.9.2/cc1", ["$HOME/local/bin/"..., "-E", "-lang-asm", "-quiet", "-nostdinc", "-iprefix", "$HOME/local/bin/"..., "-MMD", "tmp/arm64-linux.elf-entry.d", "-MT", "arm64-linux.elf-entry.h", "src/arm64-linux.elf-entry.S", "-mlittle-endian", "-mabi=lp64", "-Wall", "-Wextra", "-Wcast-align", "-Wcast-qual", "-Wstrict-prototypes", "-Wwrite-strings", "-Werror", "-fno-exceptions", "-fno-asynchronous-unwind-tables", "-fno-directives-only", "-o", "/tmp/cctjx3D0.s"], 0x19ea490 /* 82 vars */ <unfinished ...>
16345 <... execve resumed>)             = 0
16346 execve("$HOME/local/bin/bin-upx-20210104/packages/gcc-aarch64-linux-gnu-4.9.2-3.fc22.x86_64/bin/../libexec/gcc/aarch64-linux-gnu/4.9.2/as", ["$HOME/local/bin/"..., "-EL", "-mabi=lp64", "-o", "tmp/arm64-linux.elf-entry.bin", "/tmp/cctjx3D0.s"], 0x19ea490 /* 82 vars */ <unfinished ...>
16346 <... execve resumed>)             = 0
16347 execve("/usr/bin/chmod", ["chmod", "a-x", "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16347 <... execve resumed>)             = 0
16348 execve("$HOME/local/bin/bin-upx/arm64-linux-objcopy-2.25", ["arm64-linux-objcopy-2.25", "-F", "elf64-littleaarch64", "--strip-unneeded", "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16348 <... execve resumed>)             = 0
16349 execve("$HOME/local/bin/bin-upx/arm64-linux-objcopy-2.25", ["arm64-linux-objcopy-2.25", "-F", "elf64-littleaarch64", "-R", ".text", "-R", ".data", "-R", ".bss", "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16349 <... execve resumed>)             = 0
16350 execve("$HOME/local/bin/bin-upx/arm64-linux-objcopy-2.25", ["arm64-linux-objcopy-2.25", "-F", "elf64-littleaarch64", "-R", ".comment", "-R", ".note", "-R", ".note.GNU-stack", "-R", ".reginfo", "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16350 <... execve resumed>)             = 0
16351 execve("/bin/sh", ["/bin/sh", "-c", "arm64-linux-objdump-2.25 -Dr  tm"...], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16351 <... execve resumed>)             = 0
16353 execve("/usr/bin/sed", ["sed", "-e", "s/[ \t]*$//"], 0x55574e765880 /* 77 vars */) = 0
16352 execve("$HOME/local/bin/bin-upx/arm64-linux-objdump-2.25", ["arm64-linux-objdump-2.25", "-Dr", "tmp/arm64-linux.elf-entry.bin"], 0x55574e765880 /* 77 vars */) = 0
16354 execve("/bin/sh", ["/bin/sh", "-c", "arm64-linux-objdump-2.25 -htr -w"...], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16354 <... execve resumed>)             = 0
16355 execve("$HOME/local/bin/bin-upx/arm64-linux-objdump-2.25", ["arm64-linux-objdump-2.25", "-htr", "-w", "tmp/arm64-linux.elf-entry.bin"], 0x558a86e71100 /* 77 vars */ <unfinished ...>
16355 <... execve resumed>)             = 0
16356 execve("/usr/bin/sed", ["sed", "-e", "s/[ \t]*$//"], 0x558a86e71100 /* 77 vars */ <unfinished ...>
16356 <... execve resumed>)             = 0
16357 execve("/usr/bin/cat", ["cat", "--squeeze-blank"], 0x558a86e71100 /* 77 vars */ <unfinished ...>
16357 <... execve resumed>)             = 0
16358 execve("/usr/bin/sed", ["sed", "-e", "1{/^$/d}", "-e", "${/^$/d}"], 0x558a86e71100 /* 77 vars */ <unfinished ...>
16358 <... execve resumed>)             = 0
16359 execve("/usr/bin/sed", ["sed", "-e", "1s/^.*: *file format/file format"...], 0x558a86e71100 /* 77 vars */ <unfinished ...>
16359 <... execve resumed>)             = 0
16360 execve("/usr/bin/python2", ["python2", "./../../src/stub/scripts/xstrip."..., "--with-dump=tmp/arm64-linux.elf-"..., "tmp/arm64-linux.elf-entry.bin"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16360 <... execve resumed>)             = 0
16361 execve("/bin/sh", ["/bin/sh", "-c", "cat tmp/arm64-linux.elf-entry.bi"...], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16361 <... execve resumed>)             = 0
16362 execve("/usr/bin/cat", ["cat", "tmp/arm64-linux.elf-entry.bin.du"...], 0x55a243b35b90 /* 77 vars */) = 0
16363 execve("/usr/bin/python2", ["python2", "./../../src/stub/scripts/bin2h.p"..., "--ident=auto-stub", "tmp/arm64-linux.elf-entry.bin", "arm64-linux.elf-entry.h"], 0x56467faf2120 /* 79 vars */ <unfinished ...>
16363 <... execve resumed>)             = 0

$ /usr/bin/python2 --version
Python 2.7.18

$ cd $HOME/local/bin

$ find . -name arm64-linux-objcopy-2.25
./bin-upx-20210104/arm64-linux-objcopy-2.25

$ cd bin-upx-20210104

$ ls -l arm64-linux-objcopy-2.25
lrwxrwxrwx. 1 user group 84 Apr  7  2015 arm64-linux-objcopy-2.25 -> packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objcopy

$ ls -l packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objcopy
-rwxr-xr-x. 2 user group 1087424 Apr  7  2015 packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objcopy

$ ls -l arm64-linux-objdump-2.25
lrwxrwxrwx. 1 user group 84 Apr  7  2015 arm64-linux-objdump-2.25 -> packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objdump

$ ls -l packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objdump
-rwxr-xr-x. 2 user group 1546896 Apr  7  2015 packages/binutils-aarch64-linux-gnu-2.25-4.fc22.x86_64/bin/aarch64-linux-gnu-objdump
```

Please do a similar analysis in your environment.
