### ISSUE TITLE
Android packed .so crash.

### ISSUE THREAD

**Issue by ThunderMods** [upx/upx#664]
## What's the problem (or question)?
Packed .so file is crashing on Android when it's loading.

## What should have happened?
File should load without issues, and act like an original (non-compressed file)

## Do you have an idea for a solution?
Nope. I'm not familar with packing/obfuscation

## How can we reproduce the issue?

1. Compile .so file
2. In java code, write it into file in /data/user/0/package_name/files/lib.so
3. Call System.load on path where you wrote lib.
4. See the result.
I was able to get logs. It might help you, so:
2023-04-08 21:05:27.148 22665-22665 libnb                   com.axlebolt.standoff2               V  enter native_bridge2_isCompatibleWith 3
2023-04-08 21:05:27.149 22665-22665 libnb                   com.axlebolt.standoff2               V  enter native_bridge3_loadLibraryExt /data/user/0/com.axlebolt.standoff2/files/libProCode.js, 2, 0x3
2023-04-08 21:05:27.153 22665-22665 libnb                   com.axlebolt.standoff2               V  native_bridge3_loadLibraryExt: 0x0
2023-04-08 21:05:27.153 22665-22665 libnb                   com.axlebolt.standoff2               V  enter native_bridge2_isCompatibleWith 3
2023-04-08 21:05:27.153 22665-22665 libnb                   com.axlebolt.standoff2               V  enter native_bridge3_getError
2023-04-08 21:05:27.153 22665-22665 AndroidRuntime          com.axlebolt.standoff2               D  Shutting down VM
2023-04-08 21:05:27.155 22665-22665 AndroidRuntime          com.axlebolt.standoff2               E  FATAL EXCEPTION: main
                                                                                                    Process: com.axlebolt.standoff2, PID: 22665
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed
                                                                                                    	at java.lang.Runtime.load0(Runtime.java:944)
                                                                                                    	at java.lang.System.load(System.java:1639)
                                                                                                    	at com.unity3d.player.UnityPlayerActivity.test(UnityPlayerActivity.java:56)
                                                                                                    	at com.unity3d.player.UnityPlayerActivity.onCreate(Unknown Source:1)
                                                                                                    	
## Please tell us details about your environment.

upx 4.0.2
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
* Windows 10
* 64 bit.
* LDPlayer (Android 9 emulator)
* Not sure, 64-bit instance so it is probably (x86/x86_64/arm/arm64)

**Comment by ThunderMods** [comment]
I have looked through another issues and it looks like that 4.0 upx update broke android support.
I tried with 3.96, with --android-shlib flags.
upx: libmain.so: CantPackException: bad e_shoff

Btw, on 4.0.2 i packed with and without shlib - still same crash.

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or give the URL of an actual file which experiences the crash.

**Comment by ThunderMods** [comment]
[upx-4.0.2-win64.zip](https://github.com/upx/upx/files/11184283/upx-4.0.2-win64.zip)
With shlib argument, and without

**Comment by ThunderMods** [comment]
Also, packed file is .upx extension. It needs to be .upx or upx just doesnt compressed it fully?

**Comment by jreiser** [comment]
These are not legitimate executable files, neither before nor after UPX compression.  Unzipping upx-4.0.2-win64.zip gives two files
```
1933141  libmain-no-shlib.upx
1937237  libmain-shlib.upx
```
which both have the same first PT_LOAD (_`readelf --segments filename`_):
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000509d70 0x0000000000509d70  R E    0x1000
```
where the FileSiz of 0x509d70 is 5283184 which is more than the number of bytes in the file (1933141 or 1937237).

Also, each file contains only one occurrence of the three-character string `UPX`, yet the result of compression by UPX contains at least 5 instances, including the UPX copyright string:
```
$Info: This file is packed with the UPX executable packer http://upx.sf.net $
$Id: UPX 4.03 Copyright (C) 1996-2023 the UPX Team. All Rights Reserved. $
```
Removing the copyright string is a violation of the license.

**Comment by ThunderMods** [comment]
wow. Probably upx couldn't compress it fully? Cause in console it is likely stuck at 2/3:
![image](https://user-images.githubusercontent.com/101892717/230763232-121084fc-f5de-43a9-9e27-cc42c231bec1.png)
Here is original file which i'm compressing (6MB) - 
[libmain.zip](https://github.com/upx/upx/files/11185069/libmain.zip)

**Comment by ThunderMods** [comment]
I would appreciate any help, because it seems to me that upx can't fully compress my file, in the console it freezes at 2/3 and stops working, leaving me with a file with an .upx extension. I'm not very familiar with upx or packing/obfuscation, so i dont know if output file must contain .upx

**Comment by ThunderMods** [comment]
I have tried compressing .exe randomly found on my pc (adb):
![image](https://user-images.githubusercontent.com/101892717/230763360-956d462d-1fc5-400d-9b58-2178d94c8793.png)
The result of successful compression is below. While i'm packing .so files, i dont see the "Packed 1 file." line.

**Comment by ThunderMods** [comment]
@jreiser

**Comment by jreiser** [comment]
@ThunderMods Because of miscommunication and environment problems, it is time for a big RESET on this Issue.  Thank you for Attaching the original libmain.so in libmain.zip.  After investigating libmain.so, I have removed the `invalid` and `not a bug` labels.

The first problem is the Windows environment, which you discovered via the missing output `Packed 1 file` when upx-4.0.2 compressed libmain.so.   The internal culprit is a bug of de-referencing a NULL pointer.  The external culprit is that neither CMD nor PowerShell tell you that this has happened; all non-Windows shells emit on stderr a warning of `SIGSEGV`.  The deficiency of Windows was exacerbated because the initial Description omitted the exact recipe for reproducing the problem.  The initial *.upx files appeared to be renamed final output from compression, which confused me.

The "no notice of SIGSEGV" was fixed on March 4 on the `devel4` branch.  The SIGSEGV was caused by incomplete implementation for 64-bit ARM shared libraries in upx-4.0.2. Almost all of that is now complete.  But your libmain.so revealed a problem with initialization when a 64-bit shared library has no DT_INIIT, but only DT_INIT_ARRAY.  I have analyzed this, and expect a fix in the next few days.

**Comment by jreiser** [comment]
@ThunderMods  The commits above deal with the problems. To get builds, click on Actions in the menu bar just above the title on this page, then in the list click on the Commit title which has the top-most green checkmark, then scroll down to the Artifacts.

**Comment by ThunderMods** [comment]
Thanks, will check today

**Comment by jreiser** [comment]
Also check latest Actions; commit a20c5a1e7f1b4d29847628c097ed0b42f78864d0 could easily affect you.
