### ISSUE TITLE
Compressed armv8 library crashes on Android

### ISSUE THREAD

**Issue by hax0r31337** [upx/upx#669]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Compressed library causing application crash.

## What should have happened?
App should be able to launch without crash

## Do you have an idea for a solution?
No idea, I'm not familiar with native things.

## How can we reproduce the issue?

1. Download or build the [library](https://github.com/mccheatz/LibMITM)
2. Extract `libgojni.so` from built `libmitm.aar`
3. Compress the library with upx `--best --brute --android-shlib`
4. Compress the compressed library back to `libmitm.aar`
5. Build the application which requires this library, https://github.com/hax0r31337/ProtoHax-Android
6. Crash occurs

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.3-git-c72ceaa97955
* Host Operating System and version: Arch Linux 6.2.12-arch1-1
* Host CPU architecture: x86_64
* Target Operating System and version: Android 10
* Target CPU architecture: arm64-v8a
~~~
04-27 19:04:26.344 18258 18258 E AndroidRuntime: FATAL EXCEPTION: main
04-27 19:04:26.344 18258 18258 E AndroidRuntime: Process: dev.sora.protohax.netease, PID: 18258
04-27 19:04:26.344 18258 18258 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/dev.sora.protohax.netease-HMGPYCY3P6jmBQZaLLs9PQ==/lib/arm64/libgojni.so" has unsupported e_shentsize: 0x0 (expected 0x40)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1667)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at go.Seq.<clinit>(Seq.java:37)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at go.Seq.touch(Seq.java:50)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at libmitm.Libmitm.<clinit>(Libmitm.java:12)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at libmitm.Libmitm.setIdentityPublicKey(Native Method)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at dev.sora.protohax.MyApplication.onCreate(MyApplication.kt:22)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6652)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7557)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-27 19:04:26.344 18258 18258 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

~~~

**Comment by markus-oberhumer** [comment]
Please try the latest git version 726f5de778db165c1980a3f13d3c5b96b79540c2 from https://github.com/upx/upx/actions/runs/4805575565

**Comment by hax0r31337** [comment]
It stops crashing anymore, thanks :)
