### ISSUE TITLE
UPX failing to pack Rust library compiled for aarch64-linux-android

### ISSUE THREAD

**Issue by soupslurpr** [upx/upx#740]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

I am trying to use UPX to reduce the size of the .so for the Rust library for my app. Running ./upx.exe --android-shlib libbeautyxt_rs.so -o libbeautyxt_rs_compressed.so results in an error:  CantPackException: need DT_INIT; try "void _init(void){}"

## What should have happened?

It should have worked successful.

## Do you have an idea for a solution?

I don't know

## How can we reproduce the issue?

1. Compile cdylib Rust library for aarch64-linux-android
2. try to compress/pack using upx with command: ./upx.exe --android-shlib libbeautyxt_rs.so -o libbeautyxt_rs_compressed.so
3. Error occurs: CantPackException: need DT_INIT; try "void _init(void){}"

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.2.1
* Host Operating System and version: Windows 11 22H2
* Host CPU architecture: x86_64
* Target Operating System and version: GrapheneOS 2023111500 (Android 14)
* Target CPU architecture: aarch64/arm64

**Comment by soupslurpr** [comment]
Using --force-pie makes it successfully pack it, but running the app results in a crash when it tries to use the library:

```
2023-11-28 19:46:15.825 20904-20904 linker                  dev.soupslurpr.beautyxt.debug        E  "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
2023-11-28 19:46:15.826 20904-20904 linker                  dev.soupslurpr.beautyxt.debug        E  "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
2023-11-28 19:46:15.827 20904-20904 linker                  dev.soupslurpr.beautyxt.debug        E  "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
2023-11-28 19:46:15.836 20904-20904 AndroidRuntime          dev.soupslurpr.beautyxt.debug        D  Shutting down VM
2023-11-28 19:46:15.839 20904-20904 AndroidRuntime          dev.soupslurpr.beautyxt.debug        E  FATAL EXCEPTION: main
                                                                                                    Process: dev.soupslurpr.beautyxt.debug, PID: 20904
                                                                                                    java.lang.UnsatisfiedLinkError: Unable to load library 'beautyxt_rs':
                                                                                                    dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
                                                                                                    dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
                                                                                                    dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
                                                                                                    Native library (android-aarch64/libbeautyxt_rs.so) not found in resource path (.)
                                                                                                    	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
                                                                                                    	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
                                                                                                    	at com.sun.jna.Library$Handler.<init>(Library.java:197)
                                                                                                    	at com.sun.jna.Native.load(Native.java:622)
                                                                                                    	at com.sun.jna.Native.load(Native.java:596)
                                                                                                    	at dev.soupslurpr.beautyxt._UniFFILib$Companion$INSTANCE$2.invoke(beautyxt_rs.kt:1283)
                                                                                                    	at dev.soupslurpr.beautyxt._UniFFILib$Companion$INSTANCE$2.invoke(beautyxt_rs.kt:375)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at dev.soupslurpr.beautyxt._UniFFILib$Companion.getINSTANCE$app_debug(beautyxt_rs.kt:375)
                                                                                                    	at dev.soupslurpr.beautyxt.Beautyxt_rsKt.initializeWorld(beautyxt_rs.kt:1211)
                                                                                                    	at dev.soupslurpr.beautyxt.ui.TypstProjectViewModel.openProject(TypstProjectViewModel.kt:35)
                                                                                                    	at dev.soupslurpr.beautyxt.BeauTyXTKt$BeauTyXTApp$openTypstProjectLauncher$1.invoke(BeauTyXT.kt:542)
                                                                                                    	at dev.soupslurpr.beautyxt.BeauTyXTKt$BeauTyXTApp$openTypstProjectLauncher$1.invoke(BeauTyXT.kt:537)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.invoke$lambda$0(ActivityResultRegistry.kt:106)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.$r8$lambda$CrhP0xb3HsgP_dLwJEFAtzTwPms(Unknown Source:0)
                                                                                                    	at androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:2)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8999)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5537)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5583)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8199)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
                                                                                                    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
2023-11-28 19:46:15.843 20904-20904 AndroidRuntime          dev.soupslurpr.beautyxt.debug        E  		at com.sun.jna.Native.open(Native Method)
                                                                                                    		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
                                                                                                    		... 33 more
                                                                                                    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
                                                                                                    		at com.sun.jna.Native.open(Native Method)
                                                                                                    		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
                                                                                                    		... 33 more
                                                                                                    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~tArwC0k5d6pYDxeNugW1Hw==/dev.soupslurpr.beautyxt.debug-Dl_nffiZi2XmcCByxO6-4Q==/base.apk!/lib/arm64-v8a/libbeautyxt_rs.so" .dynamic section has invalid offset: 0x1813fe0, expected to match PT_DYNAMIC offset: 0x0
                                                                                                    		at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    		at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    		at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:238)
                                                                                                    		... 33 more
                                                                                                    	Suppressed: java.io.IOException: Native library (android-aarch64/libbeautyxt_rs.so) not found in resource path (.)
                                                                                                    		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
                                                                                                    		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:295)
                                                                                                    		... 33 more
```

**Comment by jreiser** [comment]
Please upload ("Paste, drop, or click to add files") or give the URL to the file `libbeautyxt_rs.so` so that the problem can be reproduced.

**Comment by soupslurpr** [comment]
Sure, here you go: https://github.com/soupslurpr/temp/blob/main/libbeautyxt_rs.so

**Comment by jreiser** [comment]
Looking at the Dynamic section via `readelf --dynamic libbeautyxt_rs.so`:
```
Dynamic section at offset 0x1814510 contains 24 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000000000007 (RELA)               0x2e90
 0x0000000000000008 (RELASZ)             1104408 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          46015
 0x0000000000000017 (JMPREL)             0x1108a8
 0x0000000000000002 (PLTRELSZ)           2136 (bytes)
 0x0000000000000003 (PLTGOT)             0x18166a0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x308
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x1a14
 0x000000000000000a (STRSZ)              5243 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1708
 0x000000000000001a (FINI_ARRAY)         0x1816500
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffff0 (VERSYM)             0x1520
 0x000000006ffffffe (VERNEED)            0x16a4
 0x000000006fffffff (VERNEEDNUM)         3
 0x0000000000000000 (NULL)               0x0
```
There is no (DT_)INIT or (DT_)INIT_ARRAY entry, so there is no way for the upx de-compression stub to gain control when this library is `dlopen`ed.  That's the meaning of the message ` CantPackException: need DT_INIT; try "void _init(void){}"`.

You could add a DT_INIT entry by compiling a file foo.c with the one line `void _init(void){}` then adding foo.o to the command which builds the shared library.  Then the upx de-compression stub can gain control.

Looking at `readelf --relocs libbeautyxt_rs.so` there are 46017 `Elf64_Rela` entries (/usr/include/elf.h) of 24 bytes each.  All but 2 of them are `R_AARCH64_RELATIVE`.  So there would be a very large space savings (about 96:1) by building the shared library with `-Wl,-z,pack-relative-relocs`, because this uses a bitmap to specify the R_RELATIVE locations, and in this case the relocations tend to be every-other word of 8 bytes.  UPX has a proposed enhancement https://github.com/upx/upx/issues/696 which would do much the same thing, but if you're building the library then you can get the savings even without such an enhancement to UPX.  The downside of `pack-relative-relocs` is that this feature is relatively new, only a couple years old, so taking the resulting binary .so file on "time travel" (using it on a system whose ld-linux.so is not new enough) will cause a fatal complaint from ld-linux.so.

The explicit `NULL` entry (`DT_NULL`) as a terminator in the Dynamic section is somewhat redundant because `Elf64_Shdr.sh_size` already specifies the total length.  So it might be possible for UPX to change the DT_NULL to DT_INIT, and thus provide a "hook" for de-compression.  But that would be an Enhancement, and there are other, much bigger, fish to fry.

**Comment by soupslurpr** [comment]
Using `-z pack-relative-relocs` results in a shared library that is only 23,704 KB. The file is here: https://github.com/soupslurpr/temp/blob/main/libbeautyxt_rs_-z_pack-relative-relocs.so

**Comment by soupslurpr** [comment]
following the directions to compile the one liner with the library resulted in the same error when running in Android. Also was the `-z pack-relative-relocs` supposed to reduce size by 96%?

**Comment by jreiser** [comment]
The estimated 96:1 reduction (eyeballed from looking at how dense the bitmap might be) is for the `.rela.dyn section`: from 0x10da18 (== 1104408) to about 12K, which would save more than a megabyte, both pre-compression and post-compression.  This is not too far from the observed (25361136 - 23704k) = 1657136.

The Linux documentation `$ info ld` says
```
‘-init=NAME’
     When creating an ELF executable or shared object, call NAME when
     the executable or shared object is loaded, by setting DT_INIT to
     the address of the function.  By default, the linker uses ‘_init’
     as the function to call.
```
Did you use /usr/bin/ld, or some other static binder, to build libbeautyxt_rs.so? It may be necessary to add some explicit command-line argument (such as `-init=NAME`) to create the DT_INIT entry in the Dynamic section.  (This might have to be expressed as `-Wl,-init=NAME` if using some "driver" command such as `gcc` to invoke the static binder.)

**Comment by soupslurpr** [comment]
Where would the command-line argument have to be specified? I'm using clang to compile libdt_init.a. I'm not sure what you mean by static binder maybe its linker? I'm using the Android NDK as the linker and llvm ar

**Comment by jreiser** [comment]
"static binding" is the precisely-correct term for what the "linker" /usr/bin/ld performs.  Common usage has corrupted and confused the terms "linker" and "loader", especially when "dynamic linking" and "dynamic loading" are also relevant.

Check the documentation (ha ha ha!) for Android NDK.  It's a Google thing, which means it is not necessarily compatible with the 40-year precedent of UNIX+Linux.  The result is chaos for developers.

**Comment by soupslurpr** [comment]
Welp I think I give up, I tried finding something in the documentation but I don't really know how to do it. Thanks for the help though and the `-z pack-relative-relocs` which is a nice reduction.

**Comment by markus-oberhumer** [comment]
@soupslurpr 

You might want to try if adding some code like this to your shared library helps:

```rust
#[no_mangle]
pub fn _init() { }
```

I'm no rust expert, though.

**Comment by soupslurpr** [comment]
@markus-oberhumer That worked! I did that and removed --force-pie and with `/upx.exe --android-shlib libbeautyxt_rs.so -o libbeautyxt_rs_compressed.so` it compressed from 23.7 MB to 17.6 MB and ran successfully on Android! Thank you

**Comment by stefano-finocchiaro-20230331** [comment]
> The explicit `NULL` entry (`DT_NULL`) as a terminator in the Dynamic section is somewhat redundant because `Elf64_Shdr.sh_size` already specifies the total length. So it might be possible for UPX to change the DT_NULL to DT_INIT, and thus provide a "hook" for de-compression. But that would be an Enhancement, and there are other, much bigger, fish to fry.

I've tried to use UPX to reduce the size of some libs but most of them fail with the same issue reported here but because they are third party libs we can't add the init function and recompile them, what about this potential enhancement ? Is it doable ?

**Comment by jreiser** [comment]
@stefano-finocchiaro-20230331 Investigation: on such a shared library, see if there is zeroed space after the last entry in PT_DYNAMIC.
```
$ readelf --segments my_lib.so
Program Headers:
  Type           Offset             VirtAddr           PhysAddr 
                 FileSiz            MemSiz              Flags  Align
  DYNAMIC        0x0000000000019b50 0x000000000001ab50 0x000000000001ab50
                 0x00000000000001f0 0x00000000000001f0  RW     0x8

$ od -Ax -tx8 -j 0x19b50  my_lib.so  |  sed 40q 
#    That dumps the whole PT_DYNAMIC, begning at file offseti 0x0000000000019b50,
#    plus a few lines after it;  40 is (0x1f0 / 16) plus a few.
```
and then look if there are at least two 64-bit words of zeroes following.

**Comment by stefano-finocchiaro-20230331** [comment]
```
root@3d5cabe9f0df:/workdir# readelf --segments libapp.so 

Elf file type is DYN (Shared object file)
Entry point 0x0
There are 7 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000188 0x0000000000000188  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000009edcf8 0x00000000009edcf8  R      0x10000
  LOAD           0x00000000009f0000 0x00000000009f0000 0x00000000009f0000
                 0x00000000014f9190 0x00000000014f9190  R E    0x10000
  LOAD           0x0000000001ef0000 0x0000000001ef0000 0x0000000001ef0000
                 0x0000000000000090 0x0000000000000090  RW     0x10000
  NOTE           0x00000000000001c8 0x00000000000001c8 0x00000000000001c8
                 0x0000000000000020 0x0000000000000020  R      0x4
  DYNAMIC        0x0000000001ef0030 0x0000000001ef0030 0x0000000001ef0030
                 0x0000000000000060 0x0000000000000060  RW     0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x1

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.gnu.build-id .rodata .eh_frame .dynstr .dynsym .hash 
   02     .text 
   03     .bss .dynamic 
   04     .note.gnu.build-id 
   05     .dynamic 
   06     
root@3d5cabe9f0df:/workdir# od -Ax -tx8 -j 0x1ef0030 libapp.so  |  sed 16q 
1ef0030 0000000000000004 00000000009edcc0
1ef0040 0000000000000005 00000000009edba8
1ef0050 000000000000000a 0000000000000085
1ef0060 0000000000000006 00000000009edc30
1ef0070 000000000000000b 0000000000000018
1ef0080 0000000000000000 0000000000000000
1ef0090 7472747368732e00 747865742e006261
1ef00a0 617461646f722e00 672e65746f6e2e00
1ef00b0 646c6975622e756e 7373622e0064692d
1ef00c0 6172665f68652e00 736e79642e00656d
1ef00d0 736e79642e007274 687361682e006d79
1ef00e0 696d616e79642e00 0000000000000063
1ef00f0 0000000000000000 0000000000000000
*
1ef0130 0000000700000019 0000000000000002
1ef0140 00000000000001c8 00000000000001c8

```
@jreiser 

Last entry seems to be all zero "1ef0080" the next after last entry is "1ef00f0"

**Comment by stefano-finocchiaro-20230331** [comment]
In another library I get this


```
root@3d5cabe9f0df:/workdir# readelf --segments libfreetype.so 

Elf file type is DYN (Shared object file)
Entry point 0x24b58
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000023b58 0x0000000000023b58  R      0x1000
  LOAD           0x0000000000023b58 0x0000000000024b58 0x0000000000024b58
                 0x00000000000b4028 0x00000000000b4028  R E    0x1000
  LOAD           0x00000000000d7b80 0x00000000000d9b80 0x00000000000d9b80
                 0x0000000000006118 0x0000000000006118  RW     0x1000
  DYNAMIC        0x00000000000dd6f0 0x00000000000df6f0 0x00000000000df6f0
                 0x0000000000000190 0x0000000000000190  RW     0x8
  GNU_RELRO      0x00000000000d7b80 0x00000000000d9b80 0x00000000000d9b80
                 0x0000000000006118 0x0000000000006480  R      0x1
  GNU_EH_FRAME   0x0000000000023b48 0x0000000000023b48 0x0000000000023b48
                 0x000000000000000c 0x000000000000000c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
  NULL           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000         0x0

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .dynstr 
   02     
   03     .dynamic 
   04     .dynamic 
   05     .dynamic 
   06     
   07     
   08     
root@3d5cabe9f0df:/workdir# od -Ax -v -tx8 -j 0xdd6f0 libfreetype.so  |  sed 30q 
0dd6f0 0000000000000001 000000000000115b
0dd700 0000000000000001 000000000000114e
0dd710 000000000000000e 0000000000001164
0dd720 000000000000001e 0000000000000008
0dd730 000000006ffffffb 0000000000000001
0dd740 0000000000000007 0000000000003bf0
0dd750 0000000000000008 0000000000007d28
0dd760 0000000000000009 0000000000000018
0dd770 000000006ffffff9 0000000000000536
0dd780 0000000000000017 000000000000b918
0dd790 0000000000000002 0000000000000bd0
0dd7a0 0000000000000003 00000000000df890
0dd7b0 0000000000000014 0000000000000007
0dd7c0 0000000000000006 00000000000002d0
0dd7d0 000000000000000b 0000000000000018
0dd7e0 0000000000000005 0000000000002a7c
0dd7f0 000000000000000a 0000000000001173
0dd800 000000006ffffef5 0000000000001c58
0dd810 0000000000000004 00000000000022a4
0dd820 000000000000001a 00000000000df6e0
0dd830 000000000000001c 0000000000000010
0dd840 0000000000000000 0000000000000000
0dd850 0000000000000000 0000000000000000
0dd860 0000000000000000 0000000000000000
0dd870 0000000000000000 0000000000000000
0dd880 0000000000000000 0000000000000000
0dd890 0000000000000000 0000000000000000
0dd8a0 0000000000000000 00000000000d8380
0dd8b0 00000000000d8380 00000000000d8380
0dd8c0 00000000000d8380 00000000000d8380
```

**Comment by jreiser** [comment]
In the first report:
> 1ef0070 000000000000000b 0000000000000018
> 1ef0080 0000000000000000 0000000000000000
> 1ef0090 7472747368732e00 747865742e006261

The 1ef0080 has the terminating DT_NULL, and 1ef0090+1 is some character string.  Even though the terminating DT_NULL is somewhat redundant (the .p_filesz of the PT_DYNAMIC fulfills much the same purpose), it cannot be used by itself because some existing code looks for the DT_NULL as a sentinel.  How important is the character string?  Could the first 15 bytes by zeroed with no bad effect?  Otherwise there is no room to squeeze-in a DT_INIT, so this library cannot be compressed.

In the second report:
```
0dd830 000000000000001c 0000000000000010
0dd840 0000000000000000 0000000000000000
0dd850 0000000000000000 0000000000000000
0dd860 0000000000000000 0000000000000000
0dd870 0000000000000000 0000000000000000
0dd880 0000000000000000 0000000000000000
0dd890 0000000000000000 0000000000000000
```
then 0dd840 has the terminating DT_NULL, and the 5 entries (16 bytes each) from 0dd850 through 0dd890 are the empty space where a DT_INIT could be added.  So this library could be compressed by using the enhancement.

**Comment by stefano-finocchiaro-20230331** [comment]
> How important is the character string?
<img width="814" alt="image" src="https://github.com/upx/upx/assets/129516000/131305ee-dea2-45bb-800e-e4c6ca6d65e2">

This is the text, I'm not sure libapp.so is the lib built by flutter sdk I need to test this, is it complicated to implement these features ? Maybe they can be implemented as optional flags like "--use-dtnull"

**Comment by stefano-finocchiaro-20230331** [comment]
This is what I've found:

https://man7.org/linux/man-pages/man5/elf.5.html


```

       .bss   This section holds uninitialized data that contributes to
              the program's memory image.  By definition, the system
              initializes the data with zeros when the program begins to
              run.  This section is of type SHT_NOBITS.  The attribute
              types are SHF_ALLOC and SHF_WRITE.

       .note.gnu.build-id
              This section is used to hold an ID that uniquely
              identifies the contents of the ELF image.  Different files
              with the same build ID should contain the same executable
              content.  See the --build-id option to the GNU linker (ld
              (1)) for more details.  This section is of type SHT_NOTE.
              The only attribute used is SHF_ALLOC.

       .shstrtab
              This section holds section names.  This section is of type
              SHT_STRTAB.  No attribute types are used.

       .text  This section holds the "text", or executable instructions,
              of a program.  This section is of type SHT_PROGBITS.  The
              attributes used are SHF_ALLOC and SHF_EXECINSTR.

       .rodata
              This section holds read-only data that typically
              contributes to a nonwritable segment in the process image.
              This section is of type SHT_PROGBITS.  The attribute used
              is SHF_ALLOC.

       .dynstr
              This section holds strings needed for dynamic linking,
              most commonly the strings that represent the names
              associated with symbol table entries.  This section is of
              type SHT_STRTAB.  The attribute type used is SHF_ALLOC.

       .dynsym
              This section holds the dynamic linking symbol table.  This
              section is of type SHT_DYNSYM.  The attribute used is
              SHF_ALLOC.

       .hash  This section holds a symbol hash table.  This section is
              of type SHT_HASH.  The attribute used is SHF_ALLOC.

       .dynamic
              This section holds dynamic linking information.  The
              section's attributes will include the SHF_ALLOC bit.
              Whether the SHF_WRITE bit is set is processor-specific.
              This section is of type SHT_DYNAMIC.  See the attributes
              above.

```
